services:
  fastapi:
    image: python:3.11-slim
    env_file:
      - .env
    container_name: fastapi-server
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "apt-get update && 
             apt-get install -y --no-install-recommends gcc python3-dev musl-dev && 
             pip install --no-cache-dir fastapi uvicorn Jinja2 couchdb2 bcrypt pyjwt[crypto] authlib httpx itsdangerous Pillow && 
             uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    restart: always
    depends_on:
        couchdb:
            condition: service_healthy

  couchdb:
    image: couchdb:3.3
    env_file:
      - .env
    container_name: couchdb-server
    volumes:
      - /volume1/docker/couchdb_data:/opt/couchdb/data
    ports:
      - "5984:5984"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 10s
      timeout: 5s
      retries: 5