# dev/gabarits_metiers.py
# Gabarits de métier des images de boutiques (dev/gen_images_magasins.py) : 10 VARIANTES par métier
# (consigne de l'auteur, 10/10 — trois jardinières de Lutecia au même chapeau et au même panier).
# Chaque boutique en reçoit une, tirée par une graine propre au lieu ; ce ne sont que des
# EXEMPLES (le prompt laisse le modèle libre d'en sortir).
#
#   PORTRAIT[cat] = (qui, [(objet présenté, tenue, décor de la boutique) × 10])   — français, §2
#   FACADE[cat]   = (boutique, [marchandises × 10])                                — anglais, §1 bis
#
# ⚠️ Aucun nom propre, aucun texte, aucun symbole religieux (docs/prompts_images.md §0).

PORTRAIT = {
	"apothicairerie": ("tient une apothicairerie", [
		("un petit flacon de remède ambré", "longue blouse tachée d'herbes, sacoche de simples", "étagères de bocaux, bouquets d'herbes séchées, mortier et pilon"),
		("un pot d'onguent ouvert", "robe de lin brun, manches nouées, bésicles sur le nez", "tiroirs étiquetés de symboles, balance à plateaux, alambic modeste"),
		("une poignée de racines noueuses", "tablier de cuir taché de teintures, foulard noué", "racines pendues aux poutres, jarres de terre, feu doux sous un chaudron"),
		("un sachet de tisane noué de ficelle", "gilet matelassé, ceinture garnie de petites fioles", "comptoir de bois sombre, sacs de fleurs séchées, pilulier de cuivre"),
		("une fiole de sirop rouge", "longue cape de voyage jetée sur une blouse claire", "armoire vitrée de remèdes, pots de miel, bouquets de lavande"),
		("un mortier de pierre plein de poudre verte", "manches retroussées, avant-bras teintés de vert", "établi encombré de graines, pilons de toutes tailles, cahiers de recettes"),
		("une bande de lin enroulée et un baume", "tunique de soignant, tablier blanc noué haut", "rouleaux de bandages, cuvettes de cuivre, chaise de consultation"),
		("une grappe de baies séchées", "chapeau mou à large bord orné d'une plume d'oiseau des marais", "guirlandes de baies et de champignons séchés, tonnelet d'eau-de-vie"),
		("une petite balance chargée de poudre", "habit sobre de lettré, plume derrière l'oreille", "rangées de boîtes de bois, registres, mesures d'étain"),
		("une branche de sauge fraîche", "sabots, jupe ou braies de toile, châle de laine", "jardinet de pots au rebord de la fenêtre, paniers de simples frais"),
	]),
	"armurerie": ("tient une armurerie", [
		("une épée fraîchement forgée", "tablier de cuir roussi, avant-bras nus couverts de suie", "enclume, forge rougeoyante, râteliers d'armes et de cottes de mailles"),
		("un heaume poli", "gambison usé, gants de forgeron", "mannequins portant des armures, chevalets de boucliers, meule"),
		("une hache de guerre", "chemise de grosse toile, tablier de cuir clouté", "haches et masses alignées au mur, soufflet de forge, seau d'eau fumant"),
		("une cotte de mailles tendue à bout de bras", "bandeau sur le front, tablier de mailles", "anneaux de mailles en vrac, pinces, rouleaux de fil de fer"),
		("un bouclier peint de motifs géométriques", "veste de cuir épaisse, manches roulées", "boucliers en cours de peinture, pots de couleur, bois de tilleul"),
		("une dague dans son fourreau", "pourpoint sombre et soigné de maître d'armes", "vitrine de lames fines, coussins de velours, présentoir de poignards"),
		("une lance au fer luisant", "tunique ceinturée, protège-bras de cuir", "hampes dressées dans un tonneau, pointes de lance sur un établi"),
		("un gantelet articulé", "chemise trempée de sueur, lunettes de forge relevées", "pièces d'armure en cours d'ajustage, marteaux à planer, rivets"),
		("une arbalète armée", "habit d'artisan sobre, ceinture d'outils", "arbalètes suspendues, carreaux en faisceaux, établi de mécanicien"),
		("une masse d'armes à ailettes", "tablier de cuir épais, tresse ou barbe nouée", "bacs de trempe, chaînes et crochets au plafond, braises vives"),
	]),
	"atelier_d_artisan": ("tient un atelier d'artisan", [
		("un coffret de bois sculpté", "tablier de travail plein de copeaux", "établi, outils de menuisier, objets ouvragés en exposition"),
		("une écuelle tournée", "chemise ouverte, sciure dans les cheveux", "tour à bois à pédale, bols et écuelles empilés"),
		("une petite chaise paillée", "tablier de toile, crayon de charpentier derrière l'oreille", "chaises et tabourets suspendus, bottes de paille de seigle"),
		("un jouet de bois peint", "gilet coloré, mains tachées de peinture", "jouets, toupies et figurines alignés, pots de couleurs vives"),
		("une cuillère sculptée", "tunique simple, couteau croche à la ceinture", "paniers de cuillères et de louches, billes de bois vert"),
		("un panier d'osier tressé", "blouse ample, brins d'osier sur les épaules", "bottes d'osier trempant dans un bac, paniers de toutes formes"),
		("un cadre de bois marqueté", "habit propre de maître artisan, loupe en sautoir", "panneaux marquetés, placages de bois précieux, presse à coller"),
		("un tonnelet cerclé de fer", "tablier de cuir, bonnet de laine", "douelles, cercles de fer, tonneaux en montage"),
		("une boîte à épices à tiroirs", "manches serrées par des liens, tablier ciré", "petits meubles à tiroirs, rabots alignés, odeur de cire"),
		("une lanterne de corne et de bois", "veste rapiécée, bottes de travail", "lanternes suspendues, plaques de corne, outils minuscules"),
	]),
	"atelier_de_cirier": ("tient un atelier de cirier", [
		("un grand cierge de cire blonde", "tablier constellé de gouttes de cire", "cuves de cire, grappes de chandelles suspendues, rayons de miel"),
		("une bougie torsadée colorée", "robe de travail, manches protégées de toile", "chandelles teintes séchant sur des perches, pots de pigment"),
		("un pain de cire d'abeille", "chapeau de toile, voile d'apiculteur rejeté en arrière", "ruches de paille, cadres de rayons, presse à miel"),
		("une poignée de mèches tressées", "gilet de laine, doigts luisants de suif", "bobines de mèche, bac de suif fondu, moules d'étain"),
		("une lanterne garnie d'une chandelle", "tablier de cuir, mitaines", "lanternes et chandeliers de fer, chandelles en paquets"),
		("un cachet de cire rouge", "habit soigné, petites taches rouges aux doigts", "bâtons de cire à cacheter, réchaud, sceaux de bois"),
		("une torche enduite de poix", "tunique sombre, tablier noirci", "torches empilées, chaudron de poix, fagots de bois résineux"),
		("une bougie parfumée dans un pot de terre", "robe claire, ceinture de fleurs séchées", "pots de bougies, bouquets de lavande, flacons d'essence"),
		("une plaque de cire à écrire", "manches retroussées, stylet derrière l'oreille", "tablettes de cire, cadres de bois, moules plats"),
		("une couronne de chandelles fines", "tablier jaune de cire, cheveux noués haut", "roue à tremper les chandelles, bains de cire successifs"),
	]),
	"atelier_de_l_empenneur": ("tient un atelier d'empenneur", [
		("une flèche finement empennée", "tablier, plumes piquées au col", "faisceaux de flèches, bottes de plumes, fûts de bois droits"),
		("une poignée de plumes d'oie triées", "gilet de cuir, loupe pendue au cou", "plumes classées par couleur, petits pots de colle, fil de lin"),
		("un fût de flèche qu'il vérifie à l'œil", "chemise de lin, brassard de cuir", "fûts bruts en bottes, rabot à fûts, gabarits de longueur"),
		("une pointe de flèche en fer", "tablier de cuir roussi, gants fins", "boîtes de pointes de toutes formes, petite forge, lime"),
		("un carquois plein de flèches", "cape courte de chasseur", "carquois suspendus, flèches de chasse et de guerre"),
		("un carreau d'arbalète", "veste matelassée, mitaines", "carreaux en caisses, empennes de cuir, étau"),
		("une flèche à empenne colorée", "tunique teinte de couleurs vives", "plumes teintes séchant sur des fils, pots de teinture"),
		("une plume de faucon", "bonnet orné d'une plume, gilet de fourrure", "plumes rares sous verre, ailes séchées, cages vides"),
		("un faisceau de flèches liées", "manches roulées, bras couverts de colle sèche", "tables de collage, fil poissé, flèches en séchage"),
		("une flèche sifflante à tête de corne", "habit sobre d'artisan âgé", "établi minutieux, outils fins, flèches spéciales en présentoir"),
	]),
	"bijouterie": ("tient une bijouterie", [
		("une bague sertie d'une pierre", "vêtements fins, loupe de bijoutier au cou", "comptoir garni d'écrins, balance de précision, petits bijoux"),
		("un collier de perles", "robe de velours sombre, gants fins", "coussins de soie, colliers en présentoir, miroir d'argent"),
		("une broche émaillée", "pourpoint brodé, chaîne d'or", "plaques d'émail, petit four, pinceaux fins"),
		("une gemme brute qu'il fait jouer dans la lumière", "tablier de cuir fin, lunettes à verres grossissants", "meule de lapidaire, gemmes triées en coupelles"),
		("un bracelet ciselé", "manches serrées, poignets nus", "établi d'orfèvre, burins, lingots minuscules"),
		("un diadème de filigrane", "habit de cour élégant", "vitrine fermée à clé, bustes de bois portant des parures"),
		("une paire de boucles d'oreilles", "tunique simple, bijoux sobres", "boîtes à compartiments, pinces, fil d'argent"),
		("un pendentif de cristal", "cape doublée de fourrure", "cristaux sur des étagères, lampe à huile, loupes sur pied"),
		("une chevalière gravée", "pourpoint sobre, doigt bagué", "matrices gravées, cire, petite presse"),
		("un médaillon qui s'ouvre", "robe ample, voile léger", "médaillons ouverts sur un drap noir, chaînettes enroulées"),
	]),
	"boucherie": ("tient une boucherie", [
		("un beau quartier de viande", "tablier taché, couperet à la ceinture", "crochets de viandes suspendues, billot de bois, étal"),
		("une couronne de saucisses", "tablier rayé, toque de toile", "saucisses pendues en guirlandes, hachoir, bassines"),
		("un gigot ficelé", "manches retroussées, bras puissants", "carcasses suspendues, scie à os, sciure au sol"),
		("un rôti paré sur une planche", "tablier de cuir propre, couteaux à la ceinture", "étal de marbre, pièces parées alignées, balance"),
		("une volaille plumée", "blouse claire, tablier noué", "volailles pendues par les pattes, plumes en sac"),
		("un pâté en croûte", "tablier blanc, foulard noué", "terrines, pâtés, bocaux de graisse"),
		("une côte de bœuf", "gilet de laine, bonnet", "billot épais, couperets alignés, seaux"),
		("un plateau d'abats", "tablier sombre, bottes de caoutchouc ciré", "bassines d'abats, crochets, glace pilée dans des bacs"),
		("un jambon frais", "chemise ouverte, tablier épais", "jambons en salaison, tonneaux, sel"),
		("un couteau qu'il aiguise sur un fusil", "tablier de cuir, manchettes", "étal garni, fusils et couteaux, morceaux choisis"),
	]),
	"boulangerie": ("tient une boulangerie", [
		("une miche de pain doré", "tablier enfariné, manches retroussées", "four à pain, corbeilles de pains et de brioches"),
		("une brioche tressée", "foulard de toile, joues rougies par le four", "pétrin de bois, pâtons qui lèvent sous des linges"),
		("une pelle à enfourner chargée de pains", "chemise trempée, tablier noué haut", "gueule du four ouverte, braises, pains en rangs"),
		("une galette aux fruits", "robe simple, tablier brodé", "galettes et tartes sur des clayettes, pots de confiture"),
		("une couronne de pain festonnée", "bonnet de boulanger, tablier épais", "pains de fête, rubans, sacs de farine"),
		("un panier de petits pains", "gilet de laine, farine sur les bras", "paniers sur le comptoir, balance, sacs de grain"),
		("un pain de seigle sombre", "chemise grossière, manches serrées", "grosses miches sombres, tonneau de levain"),
		("un plateau de biscuits au miel", "tablier fleuri, cheveux tressés", "plaques de biscuits, pots de miel, épices"),
		("une tourte dorée", "veste courte, tablier taché de fruits", "tourtes sur des grilles, fruits en corbeille"),
		("un pâton qu'il pétrit encore", "torse couvert d'une chemise légère, avant-bras puissants", "pétrin, farine en nuage, sacs empilés"),
	]),
	"cave": ("tient une cave", [
		("une bouteille de vin tenue à la lumière d'une chandelle", "tablier de cuir taché de vin, manches retroussées", "voûte de pierre, fûts alignés, chandelles dans des niches"),
		("un tastevin d'argent", "pourpoint sombre, chaîne au cou", "rangées de bouteilles couchées, casiers de bois"),
		("une cruche de terre pleine de vin", "chemise de toile, tablier de grosse toile", "tonneaux en perce, robinets de bois, sol de terre battue"),
		("un petit verre de liqueur ambrée", "gilet brodé, cheveux noués", "alambic de cuivre, flacons de liqueurs colorées"),
		("une grappe de raisin fraîchement cueillie", "chapeau de paille, tablier de vendange", "hottes de vendangeur, pressoir de bois, cuves"),
		("un pot de moutarde et une burette de vinaigre", "tablier blanc, manches serrées", "jarres de condiments, tonnelets de vinaigre, étagères"),
		("une chope de bière mousseuse", "chemise ouverte, avant-bras puissants", "cuves de brassage, sacs d'orge, fûts de chêne"),
		("un maillet de tonnelier", "tablier de cuir épais, foulard", "cercles de fer, douelles, barriques en réparation"),
		("une bougie levée vers une bouteille poussiéreuse", "manteau de laine, mitaines", "caveau profond, toiles d'araignée, bouteilles anciennes"),
		("une jarre de miel et un gobelet d'hydromel", "robe de laine brune, ceinture de cuir", "tonneaux d'hydromel, pots de miel, épices pendues"),
	]),
	"grande_boulangerie": ("tient une grande boulangerie", [
		("une couronne de pain festonnée", "tablier enfariné de maître boulanger, toque de toile", "plusieurs fours à pain, mitrons au travail, paniers de pains et de pâtisseries"),
		("une pièce montée de pâte dorée", "habit de maître soigné sous le tablier", "pâtisseries d'apparat, apprentis affairés, fours alignés"),
		("une pelle chargée de miches", "chemise trempée, toque de travers", "rangée de fours rougeoyants, mitrons portant des corbeilles"),
		("un plateau de brioches feuilletées", "tablier immaculé, gilet brodé", "comptoir de marbre, vitrines de pâtisseries"),
		("un pain de fête orné de feuillage de pâte", "foulard de toile, bras couverts de farine", "pains décorés, apprentis à la décoration"),
		("un registre de commandes et un petit pain", "pourpoint de bourgeois, plume à la main", "commis en file, sacs marqués de signes, fours au fond"),
		("une corbeille de pains variés", "tablier de toile épais", "pains de toutes formes en rayonnages, chariot de livraison"),
		("une tarte aux fruits géante", "manches retroussées, coiffe nouée", "tartes en série, fruits, pétrins mécaniques à manivelle"),
		("un sac de farine blanche ouvert", "chemise ouverte, épaules larges", "sacs de farine en piles, meunier livrant, fours"),
		("une baguette de pain longue", "tablier noué haut, bonnet de laine", "étagères chargées, foule de clients au comptoir"),
	]),
	"bourrellerie": ("tient une bourrellerie", [
		("un collier de cheval en cuir", "tablier de cuir, alêne à la ceinture", "harnais, selles et sangles pendus aux murs"),
		("une selle de voyage", "gilet de cuir, bras forts", "selles sur des chevalets, cuirs en rouleaux"),
		("une bride à boucles de laiton", "chemise de lin, tablier", "brides suspendues, boucles en boîte, pince à coudre"),
		("un bât de mule", "veste usée, bottes de cavalier", "bâts rembourrés, crins en sacs, sangles"),
		("une sacoche de selle", "tablier épais, fil poissé enroulé au poignet", "sacoches en rangées, établi de couture"),
		("une étrivière bouclée", "tunique sobre, manches nouées", "étriers de fer, étrivières, rivets"),
		("un licol neuf", "chapeau de feutre, gilet", "licols en présentoir, crochets, cuirs teints"),
		("une sangle rembourrée", "tablier taché de poix", "bourrelets de crin, poix chaude, aiguilles courbes"),
		("un fouet de cocher", "habit de voyageur, cape courte", "fouets en faisceau, harnais d'attelage"),
		("un harnais d'attelage complet", "chemise trempée, avant-bras couverts de poix", "harnais d'attelage, colliers rembourrés, chevalets"),
	]),
	"boyauderie": ("tient une boyauderie", [
		("un écheveau de corde de boyau", "tablier de cuir humide", "bacs de trempage, cordes de boyau qui sèchent sur des perches"),
		("une corde d'arc torsadée", "manches roulées, mains rougies", "rouet de torsion, cordes tendues entre deux poteaux"),
		("une baudruche gonflée", "tablier sombre, bonnet", "baudruches suspendues, bacs d'eau salée"),
		("une poignée de cordes d'instrument", "gilet propre, loupe", "cordes fines enroulées, tableaux de calibres"),
		("un boyau lavé et étiré", "tablier ciré, bottes", "bassines, tables de grattage, perches"),
		("un fil chirurgical enroulé", "blouse claire, mains propres", "fils fins en écheveaux, flacons, aiguilles"),
		("un filet de boyau tressé", "chemise de toile, bras nus", "filets en tension, cadres de bois"),
		("une saucisse vide qu'il gonfle", "tablier taché, foulard", "boyaux en saumure, tonneaux, entonnoirs"),
		("une raquette cordée", "habit simple, gants de cuir fin", "cadres en cordage, outils de tension"),
		("une corde de catapulte épaisse", "torse puissant, tablier de cuir épais", "grosses cordes, treuils, tendeurs"),
	]),
	"brosserie": ("tient une brosserie", [
		("une brosse à poils de sanglier", "tablier de toile", "brosses, balais et pinceaux de toutes tailles"),
		("un balai de genêt", "chemise de lin, sabots", "balais en bottes, genêt séché, liens d'osier"),
		("un pinceau fin", "gilet, loupe sur le nez", "pinceaux en pots, poils triés, petites viroles"),
		("une étrille et une brosse de pansage", "tablier de cuir, odeur d'écurie", "brosses de pansage, étrilles, peignes de crin"),
		("un plumeau coloré", "robe claire, ruban dans les cheveux", "plumeaux, plumes teintes, manches peints"),
		("une brosse à habits au dos sculpté", "pourpoint soigné", "brosses de toilette en vitrine, miroirs"),
		("une poignée de crins tressés", "tablier taché de poix", "crins en bottes, bacs d'eau chaude, peignes"),
		("un goupillon de ramoneur", "visage noirci, bonnet", "hérissons de fer, cordes, échelles"),
		("une brosse à chaussures et sa cire", "habit simple, manches retroussées", "brosses dures, pots de cire, sabots cirés"),
		("un pinceau de colleur", "tablier collant, bras tachés", "pinceaux larges, pots de colle, papiers"),
	]),
	"corderie": ("tient une corderie", [
		("un rouleau de corde de chanvre", "vêtements de toile, mains calleuses", "rouet de cordier, rouleaux de cordages"),
		("un cordage épais de navire", "tricot de laine, bonnet de marin", "cordages lovés, ancres, poulies"),
		("une ficelle fine en pelote", "tablier, ciseaux à la ceinture", "pelotes, écheveaux, balance"),
		("une échelle de corde", "chemise ouverte, bras tatoués de nœuds", "échelles de corde, nœuds marins en exemple"),
		("un filet de pêche", "tablier de toile goudronnée", "filets suspendus, flotteurs de liège"),
		("une corde à nœuds", "tunique de travail, gants", "cordes à grimper, crochets, mousquetons de fer"),
		("une botte de chanvre peigné", "foulard, tablier de jute", "bottes de chanvre, peignes à filasse"),
		("un lasso", "habit de voyage, chapeau de cuir", "lassos, cordes de bât, sacs"),
		("une tresse de corde colorée", "robe simple, rubans", "tresses teintes, cordelières, pompons"),
		("un câble goudronné", "chemise tachée de goudron", "chaudron de goudron, longs câbles tendus"),
	]),
	"cordonnerie": ("tient une cordonnerie", [
		("une paire de bottes neuves", "tablier de cuir, marteau de cordonnier", "formes à chaussures, établi, bottes alignées"),
		("un soulier qu'il ressemelle", "lunettes sur le nez, tablier usé", "pied de fer, clous, semelles empilées"),
		("une paire de sandales", "tunique légère, pieds nus", "sandales en présentoir, lanières de cuir"),
		("une botte de voyage cloutée", "gilet de cuir, manches retroussées", "bottes de route, clous, enclume de cordonnier"),
		("une chaussure fine brodée", "habit soigné, ciseaux d'argent", "chaussures de cour en vitrine, soieries"),
		("un sabot de bois", "sabots aux pieds, tablier de toile", "sabots sculptés, gouges, billes de bois"),
		("une forme de bois", "chemise de lin, crayon derrière l'oreille", "formes suspendues, gabarits de pieds"),
		("une paire de bottines lacées", "robe de travail, tablier", "bottines, lacets, œillets de cuivre"),
		("un chausson de laine et de cuir", "gilet de laine, bonnet", "chaussons, feutre, cuirs souples"),
		("une semelle épaisse", "tablier épais, mains noircies", "cuirs de semelle, couteau à pied, poix"),
	]),
	"cuisine": ("tient une cuisine", [
		("un bol de ragoût fumant", "tablier noué, torchon sur l'épaule", "marmites sur le feu, broche, tables de voyageurs"),
		("une broche de volailles rôties", "chemise trempée, joues rouges", "cheminée, broche tournante, odeur de rôti"),
		("une tourte fumante", "tablier fleuri, coiffe", "four de brique, tourtes, épices en pots"),
		("une louche de soupe", "manches retroussées, tablier taché", "chaudron, bols de bois, pain tranché"),
		("une assiette de poisson grillé", "veste de toile, foulard", "gril sur braises, poissons, citrons"),
		("une carafe de vin et du pain", "gilet de cuir, ceinture de clés", "tonneaux, comptoir, chopes"),
		("un plat de légumes rôtis", "robe simple, tablier", "paniers de légumes, planche à découper"),
		("une crêpe qu'il fait sauter", "bonnet, tablier blanc", "billig de fer, pâte en jatte, beurre"),
		("une écuelle de bouillie au miel", "habit de laine, bras nus", "poêlons, miel, tables communes"),
		("un saucisson tranché sur une planche", "tablier de cuir, couteau à la main", "charcuteries pendues, tables de bois, chopes"),
	]),
	"etable": ("tient une étable", [
		("un licol de cuir neuf aux boucles de laiton", "tablier de cuir, manches retroussées, brins de paille", "stalles de bois, bottes de foin, une mule et un poney"),
		("une brosse de pansage", "gilet de laine, bottes crottées", "chevaux qu'on panse, stalles, seaux"),
		("une botte de foin", "chemise de lin, chapeau de paille", "fenil, foin en meules, fourches"),
		("un fer à cheval", "tablier de maréchal, marteau", "petite forge, fers suspendus, cheval à ferrer"),
		("une selle à vendre", "veste de cavalier, éperons", "selles, harnais, chevaux sellés"),
		("un seau d'avoine", "tunique simple, sabots", "mangeoires, sacs d'avoine, ânes"),
		("une longe et un sifflet", "cape de voyage, gants", "enclos, chevaux en longe, poulains"),
		("un registre des montures", "habit de marchand de chevaux", "chevaux de prix, comptoir de vente, rubans de concours accrochés"),
		("une couverture de cheval brodée", "gilet brodé, chapeau de feutre", "couvertures pliées, harnais d'apparat"),
		("un flacon de baume pour sabots", "tablier taché, foulard", "pots de baume, outils de sabots, chèvres et moutons"),
	]),
	"fletcher": ("tient une archerie", [
		("un arc long de bois d'if", "brassard de cuir, carquois à l'épaule", "arcs suspendus, flèches en faisceaux, cibles de paille"),
		("un arc court composite", "veste de cavalier, ceinture large", "arcs recourbés, cornes, colles"),
		("une corde d'arc neuve", "tunique verte, gants d'archer", "cordes enroulées, arcs débandés"),
		("un arc de chasse orné", "cape de chasseur, capuche", "trophées de chasse, arcs de chasse, peaux"),
		("une douve d'if brute", "tablier de bois, plane à deux mains", "douves en séchage, gabarits, copeaux"),
		("une arbalète de chasse", "gilet de cuir, carreaux à la ceinture", "arbalètes, leviers, carreaux"),
		("un arc d'enfant", "habit simple, sourire", "petits arcs, flèches émoussées, jouets"),
		("une flèche qu'il tire de son carquois", "brassard clouté, plumes au chapeau", "cibles criblées, flèches plantées"),
		("un arc à double courbure", "robe de voyage, foulard", "arcs exotiques, peintures de chasse"),
		("un carquois de cuir ouvragé", "veste matelassée, ceinture d'outils", "carquois suspendus, cuirs, poinçons"),
	]),
	"fumoir": ("tient un fumoir", [
		("un jambon fumé", "tablier noirci par la fumée", "viandes et poissons pendus dans la fumée, foyer couvant"),
		("un saumon fumé", "bonnet de laine, tablier de toile", "poissons ouverts suspendus, copeaux de hêtre"),
		("une couronne de saucisses fumées", "chemise grise de fumée", "saucisses en guirlandes, foyer"),
		("une poignée de copeaux odorants", "foulard sur le nez, tablier", "sacs de copeaux, bois de chêne, braises"),
		("une pièce de lard fumé", "gilet de cuir, manches roulées", "lards pendus, crochets, tonneaux"),
		("des harengs fumés en brochette", "tablier de marin, bottes", "brochettes de harengs, caisses"),
		("une épaule de chevreuil fumée", "cape de chasseur", "gibiers fumés, bois de cerf"),
		("un fromage fumé", "tablier clair, coiffe", "fromages sur des claies, fumée douce"),
		("une anguille fumée", "chemise trempée, tablier noir", "anguilles pendues, bacs d'eau"),
		("une boîte de viande séchée", "habit de voyageur", "provisions de voyage, sacs de cuir"),
	]),
	"jardinier": ("tient une jardinerie", [
		("un panier de légumes frais", "chapeau de paille, tablier de toile terreux", "pots de plantes, semis, outils de jardin"),
		("un plant en pot de terre", "foulard noué, mains terreuses", "rangées de semis, châssis vitrés"),
		("une gerbe de fleurs coupées", "robe à fleurs, tablier", "seaux de fleurs, couronnes tressées"),
		("un sachet de graines", "gilet de laine, loupe", "tiroirs de graines, balance, cornets de papier"),
		("une serpe et une branche greffée", "veste de toile, bottes", "arbustes en bacs, greffons, raphia"),
		("une courge énorme", "chemise ouverte, chapeau de feutre", "courges et potirons, sacs de pommes de terre"),
		("un pot d'aromates", "tablier brodé d'herbes", "aromates en pots, herbes séchées"),
		("un panier de fruits", "chapeau de feuilles, robe simple", "corbeilles de fruits, échelles de cueillette"),
		("un arrosoir de cuivre", "tablier de cuir, sabots", "arrosoirs, citerne, bacs de semis"),
		("un rosier en motte", "gants de jardinier, cape courte", "rosiers, treilles, tonnelle intérieure"),
	]),
	"laboratoire_d_alchimie": ("tient un laboratoire d'alchimie", [
		("une fiole au liquide luminescent", "robe tachée, lunettes de protection relevées sur le front", "alambics, cornues, grimoires ouverts"),
		("un creuset fumant", "tablier de cuir brûlé, gants épais", "fourneau d'athanor, creusets, pinces"),
		("un cristal pris dans un étau", "habit sombre, loupe", "cristaux, instruments de mesure, sabliers"),
		("un flacon de poudre argentée", "robe brodée de symboles géométriques", "étagères de poudres, mortiers, balances"),
		("un serpentin de verre", "manches retroussées, cheveux en bataille", "verrerie complexe, bulles, vapeurs"),
		("un œuf de pierre", "cape doublée, bijoux étranges", "curiosités, bocaux de spécimens, crânes d'animaux"),
		("une potion rouge sang", "tablier taché de rouge", "fioles colorées en rang, chaudron"),
		("une sphère armillaire", "toge de savant", "pupitres, cartes des astres, astrolabe"),
		("un petit golem de glaise", "tablier de potier, mains d'argile", "glaises, moules, figurines animées"),
		("une fiole qu'il agite avec prudence", "masque de cuir abaissé au cou", "fumées colorées, fenêtre ouverte, sable"),
	]),
	"lutherie": ("tient une lutherie", [
		("un luth au bois verni", "tablier de luthier, copeaux fins", "instruments suspendus, gabarits, pots de vernis"),
		("une vielle à roue", "gilet brodé, lunettes", "vielles, roues de bois, cordes"),
		("une flûte de buis", "tunique simple, ceinture", "flûtes en faisceau, tour à bois"),
		("une harpe", "robe ample, cheveux tressés", "harpes, chevilles, colles"),
		("un tambour tendu de peau", "chemise de toile, bras forts", "tambours, peaux tendues, cercles"),
		("un violon inachevé", "tablier taché de vernis, crayon", "tables d'harmonie, moules, serre-joints"),
		("un archet", "habit sobre, mains délicates", "archets suspendus, crins, baguettes"),
		("une cornemuse", "kilt de laine, bonnet", "outres, chalumeaux, bourdons"),
		("un psaltérion", "robe de musicien", "instruments à cordes, lutrins de musiciens"),
		("un chevalet de luth à la main", "tablier de cuir, loupe", "petites pièces, chevilles, fines lames"),
	]),
	"maroquinerie": ("tient une maroquinerie", [
		("une sacoche de cuir ouvragé", "tablier de cuir, aiguilles à la ceinture", "bourses, ceintures, sacoches en exposition"),
		("une ceinture à boucle ciselée", "gilet de cuir, poinçons", "ceintures suspendues, boucles"),
		("une bourse brodée", "robe de travail, fil ciré", "bourses en rangées, cordons"),
		("une paire de gants fins", "habit soigné, gants aux mains", "gants sur des mains de bois, cuirs fins"),
		("un baudrier", "chemise de lin, bras tatoués", "baudriers, fourreaux, harnais"),
		("une gibecière", "cape de chasseur", "gibecières, carniers, cuirs bruts"),
		("un portefeuille de cuir repoussé", "tablier propre, loupe", "cuirs repoussés, emporte-pièces"),
		("un étui à dague", "veste de cuir noir", "étuis, fourreaux, lames de présentation"),
		("une besace de voyageur", "habit de route, foulard", "besaces, sacs à dos, courroies"),
		("une peau teinte qu'il examine", "manches roulées, mains teintées", "peaux teintes de couleurs, cuves"),
	]),
	"necromancie": ("tient une boutique de nécromancie", [
		("un crâne gravé de runes", "robe sombre, amulettes d'os", "ossements, bougies noires, bocaux troubles, grimoires"),
		("une fiole de brume grise", "capuche profonde, mains pâles", "fioles de brumes, cages vides, toiles d'araignée"),
		("un os de bras sculpté", "habit noir élégant, gants", "os sculptés, vitrines, chandeliers de fer"),
		("un bocal contenant un œil", "tablier taché, lunettes", "bocaux d'organes, tables de dissection"),
		("une bougie noire allumée", "robe pourpre sombre", "bougies noires en rangées, encens"),
		("un sablier de sable noir", "cape à col haut", "sabliers, horloges arrêtées, miroirs voilés"),
		("un grimoire relié de cuir sombre", "toge usée, bijoux d'argent", "grimoires sur des lutrins, plumes de corbeau"),
		("une poupée de chiffon cousue", "tunique de toile, aiguilles", "poupées, fils, cheveux tressés"),
		("un corbeau sur le poing", "manteau à plumes noires", "perchoirs, crânes d'oiseaux, cages"),
		("une urne de terre scellée", "robe grise, voile", "urnes alignées, cendres, niches"),
	]),
	"negociant": ("tient une maison de négoce", [
		("une bourse pleine et une balance", "vêtements de marchand aisé, chaîne au cou", "coffres, ballots de marchandises, registres de comptes"),
		("un rouleau d'étoffe précieuse", "pourpoint de soie", "étoffes en rouleaux, coffres ouverts"),
		("un sac d'épices ouvert", "turban, manteau de voyage", "sacs d'épices, jarres, balance"),
		("une pile de registres reliés", "habit sobre, plume", "pupitres de commis, coffres-forts"),
		("une pièce d'or qu'il fait sonner", "manteau doublé de fourrure", "changeurs, piles de monnaie, balances"),
		("une jarre d'huile", "tablier de commis", "jarres, tonneaux, entrepôt"),
		("une caisse de marchandises", "chemise ouverte, gants", "caisses empilées, porteurs, chariots"),
		("un coffret de bijoux exotiques", "vêtements de voyageur lointain", "objets exotiques, tapis, malles"),
		("un ballot de laine", "gilet de laine, chapeau", "ballots, balances à crochets"),
		("un sceau de marchand", "robe de guilde, chaîne", "comptoir massif, sceaux, cire"),
	]),
	"plumasserie": ("tient une plumasserie", [
		("un éventail de plumes chatoyantes", "vêtements soignés, plume au chapeau", "plumes multicolores en bouquets, chapeaux ornés"),
		("un chapeau à panache", "habit de cour", "chapeaux sur des têtes de bois, plumes"),
		("une plume d'autruche", "robe claire, rubans", "plumes d'autruche, vases"),
		("une parure de plumes teintes", "tablier taché de teintures", "cuves de teinture, plumes séchant"),
		("une plume d'écriture taillée", "gilet sobre, canif", "plumes d'oie taillées, encriers"),
		("un éventail de plumes de paon", "robe de soie", "plumes de paon, miroirs"),
		("une coiffe de plumes", "habit coloré, bijoux", "coiffes, masques de plumes"),
		("un oreiller de duvet", "tablier, foulard", "sacs de duvet, édredons"),
		("une boîte de plumes triées", "loupe, gilet", "boîtes à compartiments, pinces"),
		("une mouche de pêche en plumes", "habit de pêcheur", "mouches, hameçons, fils"),
	]),
	"salaison": ("tient une salaison", [
		("un saucisson sec", "tablier, mains rougies par le sel", "tonneaux de sel, jambons et saucissons pendus"),
		("un jambon salé", "chemise de toile, bras forts", "jambons sous le sel, poutres chargées"),
		("une poignée de gros sel", "tablier épais, sabots", "bacs de sel, saumures"),
		("un tonnelet de harengs saurs", "bonnet de marin", "tonneaux de poissons, sel"),
		("une terrine de rillettes", "tablier blanc, coiffe", "terrines, pots de graisse"),
		("une langue fumée", "gilet de cuir", "langues et pièces fumées, crochets"),
		("un lard entrelardé", "chemise ouverte", "lards, couteaux, planches"),
		("une morue séchée", "veste de marin", "morues séchées empilées, caisses"),
		("un bocal de cornichons", "robe simple, tablier", "bocaux, vinaigre, herbes"),
		("une bande de viande séchée", "habit de voyageur", "viandes séchées sur claies"),
	]),
	"savonnerie": ("tient une savonnerie", [
		("un pain de savon parfumé", "tablier clair, manches retroussées", "pains de savon empilés, chaudron, fioles de parfum"),
		("une louche de savon fondu", "tablier épais, gants", "chaudrons fumants, moules de bois"),
		("un savon marbré", "robe colorée, foulard", "savons marbrés, couleurs"),
		("une fiole de parfum", "habit élégant", "parfums en flacons, alambic"),
		("une boule de savon à la cendre", "chemise grossière", "cendres, lessive, bacs"),
		("un pot de crème", "blouse claire, coiffe", "pots, onguents, fleurs"),
		("un couteau qui découpe un pain de savon", "tablier de toile", "grands blocs, couteaux à savon"),
		("une bouteille d'huile de bain", "robe ample", "huiles, bassines de cuivre"),
		("un bouquet de lavande", "chapeau de paille", "lavande, savons à la lavande"),
		("un savon noir dans une écuelle", "tablier sombre", "savons noirs, potasse, jarres"),
	]),
	"scriptorium": ("tient un scriptorium", [
		("un livre relié de cuir", "robe de scribe, doigts tachés d'encre", "pupitres, encriers, parchemins, piles de livres"),
		("une plume d'oie fraîchement taillée", "habit sobre, canif", "plumes, encriers, sable à sécher"),
		("une page enluminée d'entrelacs dorés", "robe ample, loupe", "pinceaux, feuilles d'or, pigments"),
		("un rouleau de parchemin scellé", "cape de lettré", "rouleaux en casiers, cire, sceaux"),
		("une carte roulée", "gilet de voyage, compas", "cartes, globes, compas"),
		("un encrier de corne", "chemise de lin, taches d'encre", "pupitres inclinés, chandelles"),
		("un livre ouvert aux pages illustrées", "toge de savant", "bibliothèque, échelles, lutrins"),
		("une pile de feuillets", "tablier de relieur", "presses de reliure, cuirs, fils"),
		("une tablette de cire", "tunique simple", "tablettes, stylets, élèves"),
		("un grimoire fermé par un fermoir", "robe sombre brodée", "grimoires sous clé, cristaux"),
	]),
	"tabletterie": ("tient une tabletterie", [
		("un jeu d'échecs en os et ivoire", "tablier fin, loupe", "petits objets d'os et d'ivoire, peignes, dés, boîtes"),
		("un peigne d'os sculpté", "gilet, mains délicates", "peignes, épingles, petits outils"),
		("une paire de dés", "habit de joueur, sourire", "dés, gobelets, plateaux de jeu"),
		("une boîte à couvercle sculpté", "tablier, burins", "boîtes, coffrets, établi"),
		("un manche de couteau en corne", "chemise de lin", "cornes, manches, lames"),
		("une flûte d'os", "habit simple", "flûtes, sifflets, os bruts"),
		("une figurine d'animal", "robe claire, loupe", "figurines alignées, petits animaux sculptés"),
		("un éventail d'os ajouré", "habit soigné", "éventails, rubans"),
		("un jeu de dames", "gilet de laine", "pions, damiers, boîtes"),
		("une épingle à cheveux ornée", "foulard, tablier", "épingles, broches, os polis"),
	]),
	"tannerie": ("tient une tannerie", [
		("une peau tannée souple", "tablier de cuir épais, bottes hautes", "peaux tendues sur des cadres, cuves de tan"),
		("une peau qu'il racle", "bras nus, tablier taché", "chevalets de raclage, couteaux"),
		("un cuir teint en rouge", "mains teintées, foulard", "cuves de teinture, cuirs séchant"),
		("une fourrure lustrée", "gilet de fourrure", "fourrures suspendues, peaux d'hiver"),
		("un rouleau de cuir épais", "chemise grossière", "cuirs empilés, balances"),
		("une poignée d'écorce de chêne", "tablier, sabots", "écorces broyées, fosses à tan"),
		("une peau de daim", "habit de chasseur", "peaux fines, daims"),
		("un cuir bouilli moulé", "tablier épais", "moules, cuirs durcis"),
		("une peau parcheminée", "blouse claire", "peaux tendues blanches, pierres ponces"),
		("un seau de tan", "bottes, bras forts", "fosses, bassins, perches"),
	]),
	"taxidermie": ("tient un cabinet de taxidermie", [
		("un renard naturalisé", "blouse de travail, outils fins", "animaux naturalisés, têtes de cerfs, bocaux de spécimens"),
		("un hibou sur une branche", "lunettes, gilet", "oiseaux naturalisés, perchoirs"),
		("une tête de sanglier", "tablier de cuir", "trophées, défenses, peaux"),
		("un papillon sous verre", "habit soigné, loupe", "boîtes d'insectes, épingles"),
		("un serpent en spirale", "gants fins", "reptiles, bocaux"),
		("un œil de verre", "blouse tachée", "yeux de verre, pinces"),
		("un lièvre en pose", "gilet de chasseur", "petit gibier, socles"),
		("un crâne de cerf", "habit sombre", "bois de cerfs, crânes"),
		("un poisson naturalisé", "veste de pêcheur", "poissons sur planches"),
		("une chauve-souris aux ailes ouvertes", "robe sombre", "curiosités, animaux nocturnes"),
	]),
	"tissage": ("tient un atelier de tissage", [
		("une étoffe richement tissée", "vêtements de toile fine", "métier à tisser, rouleaux d'étoffes colorées"),
		("une navette de bois", "tablier, cheveux tressés", "grand métier, fils tendus"),
		("un écheveau de laine teinte", "mains colorées, foulard", "cuves de teinture, laines séchant"),
		("une tapisserie roulée", "robe longue", "tapisseries suspendues, cadres"),
		("un coupon de lin", "chemise de lin", "rouleaux de lin, ciseaux"),
		("une quenouille chargée", "habit simple, sabots", "rouets, quenouilles"),
		("un châle brodé", "robe brodée", "broderies, tambours à broder"),
		("un drap de laine foulée", "tablier humide", "fouloir, bacs d'eau"),
		("un ruban de soie", "habit élégant", "rubans, soieries"),
		("une couverture épaisse", "gilet de laine", "couvertures pliées, toisons"),
	]),
}

FACADE = {
	"apothicairerie": ("apothecary shop", [
		"shelves of jars and vials, bunches of dried herbs, mortar and pestle",
		"drawers of remedies, a small copper still, pots of salve",
		"hanging roots and dried mushrooms, earthen jars, a simmering pot",
		"bags of dried flowers, a scale, little bottles of syrup",
		"lavender bunches, honey pots, a glass cabinet of remedies",
		"seeds, pestles of every size, a bench covered in powders",
		"rolls of bandages, copper basins, a patient's chair",
		"strings of dried berries, a small keg, herb bundles",
		"rows of small wooden boxes, pewter measures, a ledger",
		"window-box of fresh herbs, baskets of simples",
	]),
	"armurerie": ("armorer's forge and shop", [
		"racks of swords and spears, chainmail shirts, helmets, glowing forge",
		"armor on wooden stands, shields on trestles, a grindstone",
		"axes and maces on the wall, bellows, a steaming water bucket",
		"loose mail rings, pliers, coils of iron wire",
		"half-painted shields with geometric patterns, pots of paint",
		"a case of fine blades, velvet cushions, daggers on display",
		"spear shafts standing in a barrel, spearheads on a bench",
		"armor pieces being fitted, planishing hammers, rivets",
		"crossbows hanging, bundles of bolts, a mechanic's bench",
		"quenching tubs, chains and hooks, live embers",
	]),
	"atelier_d_artisan": ("woodcarver's workshop", [
		"carved wooden boxes, bowls and chairs, workbench with tools",
		"a treadle lathe, stacked bowls and platters",
		"chairs and stools hanging, bundles of rye straw",
		"painted wooden toys, spinning tops, pots of bright paint",
		"baskets of carved spoons and ladles, green wood logs",
		"woven wicker baskets, osier soaking in a tub",
		"marquetry panels, veneers, a gluing press",
		"barrel staves, iron hoops, casks being assembled",
		"small chests of drawers, planes in a row",
		"horn and wood lanterns, tiny tools",
	]),
	"atelier_de_cirier": ("chandler's workshop", [
		"bunches of hanging candles, large wax tapers, vats of wax, honeycombs",
		"colored candles drying on rods, pigment pots",
		"straw beehives, honeycomb frames, a honey press",
		"spools of wick, a tub of melted tallow, pewter molds",
		"iron lanterns and candlesticks, packets of candles",
		"sticks of sealing wax, a small burner, wooden seals",
		"stacked torches, a cauldron of pitch, resinous wood",
		"candles in earthen pots, lavender, essence flasks",
		"wax writing tablets, wooden frames, flat molds",
		"a candle-dipping wheel, successive wax baths",
	]),
	"atelier_de_l_empenneur": ("fletcher's workshop", [
		"bundles of arrows, sheaves of feathers, straight wooden shafts",
		"feathers sorted by color, glue pots, linen thread",
		"bundles of raw shafts, a shaft plane, length gauges",
		"boxes of arrowheads of every shape, a small forge",
		"quivers hanging, hunting and war arrows",
		"crates of crossbow bolts, leather fletchings, a vise",
		"dyed feathers drying on strings",
		"rare feathers under glass, dried wings",
		"gluing tables, arrows drying in racks",
		"a careful workbench, fine tools, special arrows on display",
	]),
	"bijouterie": ("jeweler's shop", [
		"counter with open jewel cases, rings, necklaces, small precision scale",
		"silk cushions, pearl necklaces on display, a silver mirror",
		"enamel plates, a small kiln, fine brushes",
		"a lapidary wheel, gems sorted in little dishes",
		"a goldsmith's bench, gravers, tiny ingots",
		"a locked showcase, wooden busts wearing jewelry",
		"compartment boxes, tweezers, silver wire",
		"crystals on shelves, an oil lamp, magnifiers on stands",
		"engraved signet dies, wax, a small press",
		"open lockets on black cloth, coiled chains",
	]),
	"boucherie": ("butcher's shop", [
		"meat hanging from hooks, wooden chopping block, cuts of meat on the counter",
		"garlands of sausages, a cleaver, basins",
		"hanging carcasses, a bone saw, sawdust on the floor",
		"a marble counter, trimmed cuts in rows, a scale",
		"plucked poultry hanging by the feet, sacks of feathers",
		"terrines, pies, jars of lard",
		"a thick block, cleavers in a row, buckets",
		"basins of offal, hooks, tubs of crushed ice",
		"fresh hams, barrels, salt",
		"a well-stocked counter, knives and sharpening steels",
	]),
	"boulangerie": ("bakery", [
		"baskets of golden loaves and brioches, bread oven glowing inside",
		"a wooden kneading trough, dough rising under cloths",
		"the open oven mouth, embers, loaves in rows",
		"fruit galettes and tarts on racks, jam pots",
		"festive bread crowns, ribbons, sacks of flour",
		"baskets of small rolls on the counter, a scale",
		"big dark rye loaves, a barrel of sourdough",
		"trays of honey biscuits, spices",
		"golden pies on racks, baskets of fruit",
		"a kneading trough, clouds of flour, stacked sacks",
	]),
	"cave": ("wine cellar and liquor shop", [
		"rows of oak barrels with wooden taps, bottles on racks, a vaulted stone cellar behind",
		"bottles lying in wooden racks, a tasting cup on the counter",
		"tapped casks, earthenware jugs, a beaten earth floor",
		"a copper still, small flasks of colored liqueurs",
		"grape harvest baskets, a wooden wine press, vats",
		"jars of mustard, small casks of vinegar, shelves of condiments",
		"brewing vats, sacks of barley, frothy jugs of ale",
		"iron hoops, staves, barrels being repaired",
		"dusty old bottles, candles in wall niches, cobwebs",
		"casks of mead, honey pots, hanging bunches of spices",
	]),
	"grande_boulangerie": ("large master bakery", [
		"several glowing bread ovens, bakers' boys at work, piles of loaves, pastries and festive bread crowns",
		"showpiece pastries, busy apprentices, ovens in a row",
		"a row of glowing ovens, boys carrying bread baskets",
		"a marble counter, pastry showcases",
		"decorated festive loaves, apprentices decorating",
		"clerks in line, marked sacks, ovens at the back",
		"shelves of breads of every shape, a delivery cart",
		"rows of fruit tarts, crank-handled kneading troughs",
		"piles of flour sacks, a miller delivering, ovens",
		"loaded shelves, a crowd of customers at the counter",
	]),
	"bourrellerie": ("saddler's and harness maker's shop", [
		"saddles, harnesses, horse collars and straps hanging on the walls",
		"saddles on trestles, rolls of leather",
		"hanging bridles, boxes of buckles, a stitching clamp",
		"padded pack saddles, sacks of horsehair, girths",
		"rows of saddlebags, a sewing bench",
		"iron stirrups, stirrup leathers, rivets",
		"halters on display, hooks, dyed leathers",
		"horsehair pads, hot pitch, curved needles",
		"bundles of coachman's whips, draft harnesses",
		"full draft harnesses, padded collars, trestles",
	]),
	"boyauderie": ("gut-string maker's workshop", [
		"gut strings drying on poles, soaking tubs",
		"a twisting wheel, strings stretched between posts",
		"inflated bladders hanging, tubs of brine",
		"fine strings coiled, gauge boards",
		"basins, scraping tables, poles",
		"fine thread in skeins, flasks, needles",
		"gut nets on frames",
		"guts in brine, barrels, funnels",
		"strung racket frames, tensioning tools",
		"thick ropes, winches, tensioners",
	]),
	"brosserie": ("brush maker's shop", [
		"brushes, brooms and paintbrushes of every size",
		"bundles of broom, dried broom plant, wicker ties",
		"paintbrushes in pots, sorted bristles, small ferrules",
		"grooming brushes, curry combs, horsehair combs",
		"colorful feather dusters, painted handles",
		"toilet brushes in a showcase, mirrors",
		"bundles of horsehair, hot water tubs, combs",
		"iron chimney brushes, ropes, ladders",
		"stiff brushes, pots of wax, polished clogs",
		"wide paste brushes, glue pots, papers",
	]),
	"corderie": ("rope maker's workshop", [
		"coils of hemp rope, rope-making wheel",
		"coiled ship's hawsers, anchors, pulleys",
		"balls of fine twine, skeins, a scale",
		"rope ladders, sailor's knots on display",
		"fishing nets hanging, cork floats",
		"climbing ropes, hooks, iron rings",
		"bundles of combed hemp, flax combs",
		"lassos, pack ropes, sacks",
		"dyed braids, cords, tassels",
		"a tar cauldron, long cables stretched out",
	]),
	"cordonnerie": ("cobbler's shop", [
		"rows of leather boots and shoes, shoe lasts, workbench",
		"an iron last, nails, stacked soles",
		"sandals on display, leather straps",
		"hobnailed travel boots, a cobbler's anvil",
		"embroidered court shoes in a showcase, silks",
		"carved wooden clogs, gouges, wood blocks",
		"hanging lasts, foot patterns",
		"laced ankle boots, laces, copper eyelets",
		"felt and leather slippers, soft leathers",
		"sole leathers, a shoemaker's knife, pitch",
	]),
	"cuisine": ("cookshop", [
		"pots on the fire, roasting spit, steaming stew bowls, tables for travelers",
		"a hearth, a turning spit, roast fowl",
		"a brick oven, pies, pots of spices",
		"a cauldron, wooden bowls, sliced bread",
		"a grill over embers, fish, lemons",
		"barrels, a counter, tankards",
		"baskets of vegetables, a chopping board",
		"an iron griddle, bowls of batter, butter",
		"skillets, honey, long common tables",
		"hanging charcuterie, wooden tables, tankards",
	]),
	"etable": ("stable", [
		"wooden stalls, hay bales, a mule and a pony, harnesses",
		"horses being groomed, stalls, buckets",
		"a hayloft, haystacks, pitchforks",
		"a small forge, hanging horseshoes, a horse being shod",
		"saddles, harnesses, saddled horses",
		"mangers, sacks of oats, donkeys",
		"a paddock, horses on a lunge line, foals",
		"fine horses, a trading counter",
		"folded horse blankets, parade harness",
		"pots of hoof balm, hoof tools, goats and sheep",
	]),
	"fletcher": ("bowyer and fletcher shop", [
		"longbows hanging, bundles of arrows, quivers, straw targets",
		"recurved bows, horn, glues",
		"coiled bowstrings, unstrung bows",
		"hunting trophies, hunting bows, pelts",
		"yew staves drying, templates, shavings",
		"crossbows, levers, bolts",
		"small bows, blunt arrows, toys",
		"targets riddled with arrows",
		"exotic bows, painted hunting scenes",
		"hanging leather quivers, punches",
	]),
	"fumoir": ("smokehouse", [
		"hams, sausages and fish hanging in the smoke, smoldering hearth",
		"split salmon hanging, beech chips",
		"garlands of smoked sausages, a hearth",
		"sacks of wood chips, oak logs, embers",
		"hanging slabs of bacon, hooks, barrels",
		"skewers of herring, crates",
		"smoked game, antlers",
		"cheeses on racks, gentle smoke",
		"hanging eels, water tubs",
		"travel provisions, leather bags",
	]),
	"jardinier": ("gardener's shop", [
		"potted plants, seedlings, baskets of vegetables, garden tools",
		"rows of seedlings under glass frames",
		"buckets of cut flowers, woven wreaths",
		"drawers of seeds, a scale, paper cones",
		"shrubs in tubs, grafts, raffia",
		"pumpkins and squashes, sacks of turnips",
		"potted herbs, drying herbs",
		"baskets of fruit, picking ladders",
		"copper watering cans, a cistern, seed trays",
		"rose bushes, trellises, an indoor arbor",
	]),
	"laboratoire_d_alchimie": ("alchemist's laboratory", [
		"alembics, retorts, glowing vials, open grimoires",
		"an athanor furnace, crucibles, tongs",
		"crystals, measuring instruments, hourglasses",
		"shelves of powders, mortars, scales",
		"intricate glassware, bubbles, vapors",
		"curiosities, specimen jars, animal skulls",
		"rows of colored vials, a cauldron",
		"lecterns, star charts, an astrolabe",
		"clays, molds, small animated figurines",
		"colored fumes, sand, an open window",
	]),
	"lutherie": ("luthier's workshop", [
		"lutes, fiddles and harps hanging, varnish pots",
		"hurdy-gurdies, wooden wheels, strings",
		"bundles of flutes, a wood lathe",
		"harps, tuning pegs, glues",
		"drums with stretched skins, hoops",
		"soundboards, molds, clamps",
		"hanging bows, horsehair, sticks",
		"bagpipes, chanters, drones",
		"stringed instruments of every kind",
		"small parts, pegs, fine blades",
	]),
	"maroquinerie": ("leather goods shop", [
		"leather bags, purses, belts and satchels on display",
		"hanging belts, chased buckles",
		"embroidered purses in rows, cords",
		"gloves on wooden hands, fine leathers",
		"baldrics, scabbards, harnesses",
		"game bags, raw leathers",
		"embossed leather, punches",
		"sheaths, scabbards, display blades",
		"travel bags, backpacks, straps",
		"leathers dyed in many colors, vats",
	]),
	"necromancie": ("necromancer's shop", [
		"skulls, bones, black candles, murky jars, dark grimoires",
		"vials of grey mist, empty cages, cobwebs",
		"carved bones, showcases, iron candlesticks",
		"jars of organs, dissection tables",
		"rows of black candles, incense",
		"hourglasses, stopped clocks, veiled mirrors",
		"grimoires on lecterns, raven feathers",
		"rag dolls, threads, braided hair",
		"perches, bird skulls, cages",
		"rows of sealed urns, ashes, niches",
	]),
	"negociant": ("merchant trading house", [
		"chests, bales of goods, barrels, ledgers and a balance scale",
		"rolls of precious fabric, open chests",
		"sacks of spices, jars, a scale",
		"clerks' desks, strongboxes",
		"money changers, stacks of coins, scales",
		"jars, barrels, a warehouse",
		"stacked crates, porters, carts",
		"exotic objects, rugs, trunks",
		"bales of wool, hook scales",
		"a massive counter, seals, wax",
	]),
	"plumasserie": ("plumassier's shop", [
		"bouquets of colorful feathers, plumed hats, feather fans",
		"hats on wooden heads, plumes",
		"ostrich plumes in vases",
		"dye vats, feathers drying",
		"cut quill pens, inkwells",
		"peacock feathers, mirrors",
		"feather headdresses and masks",
		"sacks of down, eiderdowns",
		"compartment boxes, tweezers",
		"fishing flies, hooks, threads",
	]),
	"salaison": ("salting house", [
		"open barrels heaped with coarse white salt, hanging hams and dry sausages",
		"hams under salt, loaded beams",
		"tubs of salt, brines",
		"barrels of salted herring",
		"terrines, pots of lard",
		"smoked tongues and cuts, hooks",
		"slabs of bacon, knives, boards",
		"stacked dried cod, crates",
		"jars of pickles, vinegar, herbs",
		"dried meats on racks",
	]),
	"savonnerie": ("soap maker's shop", [
		"stacked bars of soap, cauldron, perfume flasks",
		"steaming cauldrons, wooden molds",
		"marbled soaps, colors",
		"perfume bottles, a still",
		"ash, lye, tubs",
		"jars, ointments, flowers",
		"large blocks, soap knives",
		"oils, copper basins",
		"lavender, lavender soaps",
		"black soap, potash, jars",
	]),
	"scriptorium": ("scriptorium and bookshop", [
		"writing desks, inkwells, parchments, stacks of leather-bound books",
		"quills, inkwells, drying sand",
		"brushes, gold leaf, pigments",
		"scroll racks, wax, seals",
		"rolled maps, globes, compasses",
		"slanted desks, candles",
		"a library, ladders, lecterns",
		"binding presses, leathers, threads",
		"wax tablets, styluses, pupils",
		"locked grimoires, crystals",
	]),
	"tabletterie": ("bone and ivory carver's shop", [
		"carved combs, dice, chess sets, small bone boxes",
		"combs, pins, small tools",
		"dice, cups, game boards",
		"carved boxes, caskets, a workbench",
		"horn, knife handles, blades",
		"bone flutes, whistles, raw bones",
		"rows of small carved animal figurines",
		"pierced bone fans, ribbons",
		"draughts pieces, checkerboards, boxes",
		"hairpins, brooches, polished bone",
	]),
	"tannerie": ("tannery", [
		"hides stretched on frames, tanning vats",
		"scraping beams, knives",
		"dye vats, leathers drying",
		"hanging furs, winter pelts",
		"stacked leathers, scales",
		"crushed bark, tanning pits",
		"fine skins, deerskins",
		"molds, hardened leathers",
		"white stretched skins, pumice stones",
		"pits, basins, poles",
	]),
	"taxidermie": ("taxidermist's cabinet", [
		"stuffed animals, deer heads, specimen jars",
		"stuffed birds, perches",
		"trophies, tusks, pelts",
		"boxes of insects, pins",
		"reptiles, jars",
		"glass eyes, tweezers",
		"small game on stands",
		"antlers, skulls",
		"fish on boards",
		"curiosities, nocturnal animals",
	]),
	"tissage": ("weaver's workshop", [
		"loom, rolls of colorful fabric",
		"a big loom, stretched threads",
		"dye vats, wool drying",
		"hanging tapestries, frames",
		"rolls of linen, scissors",
		"spinning wheels, distaffs",
		"embroideries, embroidery hoops",
		"a fulling mill, water tubs",
		"ribbons, silks",
		"folded blankets, fleeces",
	]),
}
